### ISSUE TITLE
'npm start' error

### ISSUE THREAD

**Issue by ghost** [screeninvader/outta_space#11]
cloned and installed in debian/sid, 'npm start' gives a npm-debug.log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@1.4.21
3 info using node@v0.10.29
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart outta_space@0.0.1
6 info start outta_space@0.0.1
7 verbose unsafe-perm in lifecycle true
8 info outta_space@0.0.1 Failed to exec start script
9 error outta_space@0.0.1 start: `watchify -d  src/main.js -t babelify -o bundle.js`
9 error Exit status 127
10 error Failed at the outta_space@0.0.1 start script.
10 error This is most likely a problem with the outta_space package,
10 error not with npm itself.
10 error Tell the author that this fails on your system:
10 error     watchify -d  src/main.js -t babelify -o bundle.js
10 error You can get their info via:
10 error     npm owner ls outta_space
10 error There is likely additional logging output above.
11 error System Linux 3.16.0-4-amd64
12 error command "/usr/bin/nodejs" "/usr/bin/npm" "start"
13 error cwd /home/mn/outta_space
14 error node -v v0.10.29
15 error npm -v 1.4.21
16 error code ELIFECYCLE
17 verbose exit [ 1, true ]

Thanks if solution is known.

**Comment by phaer** [comment]
Did you run `npm install`? If so: What's the output if you run `watchify -d src/main.js -t babelify -o bundle.js` directly from your shell?

**Comment by ghost** [comment]
Yea did install, got a (outside osx ignorable) fsevent warning...
I googled a solution via here: https://github.com/joyent/node/issues/3911 (funny thread btw)

So 'ln -s /usr/bin/nodejs /usr/bin/node' before 'npm start' did it.

Now crossing finger i can doctor the SI build :) 

Cheers

**Comment by jaeh** [comment]
the same problem is present on ubuntu and debian (afaik)

there was a preexisting package called node in the apt packages so they needed to use nodejs.

in apt there is a package called nodejs-legacy or node-legacy which does nothing but creating that same symlink, there may also be in homebrew
